[package]
name = "displayconfig"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = true
lto = true

[dependencies]
core-graphics = "0.23"
objc2 = "0.6"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
ctrlc = "3"

[build-dependencies]
bindgen = "0.70"


# Mode 48 -- we were on mode 80
